# Generated by Django 5.1.5 on 2025-01-26 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
    ]
