name: CI

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
  
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Test with pytest
        run: docker compose run --remove-orphans api pytest
      - name: Lint with ruff
        run: docker compose run --remove-orphans api ruff check
      - name: Check code formatting with Ruff
        run: docker compose run --remove-orphans api ruff format
        continue-on-error: true
