name: Docker CI

on:
  push:
    branches: [ "main" ]
    paths: 
      - ".github/workflows/docker-ci.yml"
  pull_request:
    branches: [ "main" ]

jobs:

  test-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Test with pytest
      run: docker compose run --remove-orphans api pytest

    - name: Lint with ruff
      run: docker compose run --remove-orphans api ruff check

    - name: Check code formatting with Ruff
      run: docker compose run --remove-orphans api ruff format

      continue-on-error: true
