name: Docker CI

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  test-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Load .env file
      uses: aarcangeli/load-dotenv@v1
      with:
        path: ','
        filenames: '.env'

          
    - name: Test with pytest
      run: docker compose run --rm api pytest

    - name: Lint with ruff
      run: docker compose run --rm api ruff check

    - name: Check code formatting with Ruff
      run: docker compose run --rm api ruff format

      continue-on-error: true
