name: Docker CI

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:

  test-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Test with pytest
      run: docker compose -f compose.yaml run --rm api pytest

    - name: Lint with ruff
      run: docker compose run -f compose.yaml --rm api ruff check

    - name: Check code formatting with Ruff
      run: docker compose run -f compose.yaml --rm api ruff format

      continue-on-error: true
