name: Docker CI

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  test-lint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Create .env file
      run: |
        touch .env
        echo '${{ secrets.SECRETS }}' >> .env
    
    - name: Create db/password file
      run: |
        mkdir db
        cd db
        touch db/password.txt
        echo '${{ secrets.DB_PASSWORD }}' >> password.txt
          
    - name: Test with pytest
      run: docker compose run --rm api pytest

    - name: Lint with Flake8
      run: docker compose run --rm api flake8

      continue-on-error: true
